"""create indexable_links and indexable_articles table

Revision ID: d03121379830
Revises: 
Create Date: 2021-07-22 14:18:36.401185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd03121379830'
down_revision = None
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_engine1():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_indexable_link',
    sa.Column('article_id', sa.String(length=260), nullable=False),
    sa.Column('link', sa.String(length=2000), nullable=True),
    sa.Column('site_name', sa.String(length=70), nullable=True),
    sa.Column('scraped_on', sa.DateTime(), nullable=True),
    sa.Column('pub_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('article_id')
    )
    op.create_index(op.f('ix_article_indexable_link_article_id'), 'article_indexable_link', ['article_id'], unique=False)
    op.create_index(op.f('ix_article_indexable_link_link'), 'article_indexable_link', ['link'], unique=False)
    op.create_table('indexable_links',
    sa.Column('link', sa.String(length=2000), nullable=False),
    sa.Column('scraped_on', sa.DateTime(), nullable=True),
    sa.Column('source_name', sa.String(length=75), nullable=True),
    sa.PrimaryKeyConstraint('link')
    )
    op.create_index(op.f('ix_indexable_links_link'), 'indexable_links', ['link'], unique=False)
    # ### end Alembic commands ###


def downgrade_engine1():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_indexable_links_link'), table_name='indexable_links')
    op.drop_table('indexable_links')
    op.drop_index(op.f('ix_article_indexable_link_link'), table_name='article_indexable_link')
    op.drop_index(op.f('ix_article_indexable_link_article_id'), table_name='article_indexable_link')
    op.drop_table('article_indexable_link')
    # ### end Alembic commands ###


def upgrade_engine2():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_indexable_link',
    sa.Column('article_id', sa.String(length=260), nullable=False),
    sa.Column('link', sa.String(length=2000), nullable=True),
    sa.Column('site_name', sa.String(length=70), nullable=True),
    sa.Column('scraped_on', sa.DateTime(), nullable=True),
    sa.Column('pub_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('article_id')
    )
    op.create_index(op.f('ix_article_indexable_link_article_id'), 'article_indexable_link', ['article_id'], unique=False)
    op.create_index(op.f('ix_article_indexable_link_link'), 'article_indexable_link', ['link'], unique=False)
    op.create_table('indexable_links',
    sa.Column('link', sa.String(length=2000), nullable=False),
    sa.Column('scraped_on', sa.DateTime(), nullable=True),
    sa.Column('source_name', sa.String(length=75), nullable=True),
    sa.PrimaryKeyConstraint('link')
    )
    op.create_index(op.f('ix_indexable_links_link'), 'indexable_links', ['link'], unique=False)
    # ### end Alembic commands ###


def downgrade_engine2():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_indexable_links_link'), table_name='indexable_links')
    op.drop_table('indexable_links')
    op.drop_index(op.f('ix_article_indexable_link_link'), table_name='article_indexable_link')
    op.drop_index(op.f('ix_article_indexable_link_article_id'), table_name='article_indexable_link')
    op.drop_table('article_indexable_link')
    # ### end Alembic commands ###

